- TalkIn/app/build.gradle
Fixes https://github.com/Ijaiswalshivam/Talk-In/issues/32, changed targetSdk to 33 and compileSdk to 34.
> Fix #32: Incompatible sdk.

- TalkIn/build.gradle
Fixes #35.
Changed 'com.google.gms:google-services:4.3.10' to 'com.google.gms:google-services:4.3.8'
> Fix #35: Default FirebaseApp is not initialized in this process com.example.talk_in.

- TalkIn/.idea/misc.xml
- TalkIn/app/src/main/res/drawable/custom_edit_text.xml
- TalkIn/app/src/main/res/layout/activity_log_in.xml
- TalkIn/app/src/main/res/layout/activity_sign_up.xml
Login and Signup page UI has been enhanced
> UI Enhancement #21

- TalkIn/app/src/main/java/com/example/talk_in/Message.kt
- TalkIn/app/src/main/java/com/example/talk_in/MessageAdapter.kt
> Fix Indentation

- TalkIn/app/src/main/java/com/example/talk_in/Message.kt
Added toast to show the timestamp when the message was sent.
Note : The message part is not fully implemented.
> feat : Add toast to show the timestamp when the message was sent.

- TalkIn/.idea/compiler.xml
- TalkIn/.idea/deploymentTargetDropDown.xml
- TalkIn/.idea/gradle.xml
- TalkIn/.idea/kotlinc.xml
- TalkIn/.idea/migrations.xml
- TalkIn/.idea/misc.xml
- TalkIn/app/src/main/java/com/example/talk_in/EntryActivity.kt
When a user is logged in, they will be redirected to MainActivity instead of EntryActivity.
#54
> Fixed : Always asking for sign-in when app is reopened

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/pull_request_template.md
**fixes#72.**
This PR creates  a proper , precise and short template for a PULL REQUEST.
Empty PR space will be filled with the created template that allows contributors to make proper informative and precise pull requests .
Contributors ponder less thinking about how to start and compose PR.
This gives a direction in writing Pull Requests.
IT saves time in understanding PR to the viewers.
Let us make TALK-IN the best!! 
thanks .
> Created Pull request template #72

- TalkIn/app/src/main/res/values-night/themes.xml
- TalkIn/app/src/main/res/values/themes.xml
Change the top bar colour to black with looks nice
> SetTopAppBarColor

- TalkIn/.idea/gradle.xml
- TalkIn/app/src/main/res/values/themes.xml
> Login button bug issue in light theme #82 Issue

- TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
- TalkIn/app/src/main/res/drawable/baseline_person_24.xml
- TalkIn/app/src/main/res/layout/activity_log_in.xml
- TalkIn/app/src/main/res/layout/activity_sign_up.xml
issue Design Signup activity #84 resolved
> Improved SignUp UI #84 issue resolved

- TalkIn/.idea/gradle.xml
- TalkIn/app/src/main/java/com/example/talk_in/EntryActivity.kt
Bug fixed : After signup it redirects to the MainActivity without verifying mail when reopens the app  #96 issues @Ijaiswalshivam
> Bug fixed : After signup it redirects to the mainActivity without verifying mail when reopens the app  #96 issues

- TalkIn/build.gradle
> There were some issues with build.gradle file

- TalkIn/app/src/main/java/com/example/talk_in/EntryActivity.kt
- TalkIn/app/src/main/java/com/example/talk_in/LogIn.kt
#121 Sign In page issue fixed. After entering email and password if user is not verified then they will get verification link on their email and if user is not verified then user cannot Sign In.
> Sign In verification issue fixed

- TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
#121 #95 You can now signup using email id and then verify your email id also.
> Fixed verification issue and email already exists issue in signup page

- TalkIn/.idea/gradle.xml
- TalkIn/app/src/main/java/com/example/talk_in/LogIn.kt
- TalkIn/app/src/main/java/com/example/talk_in/MobileAuthActivity.kt
- TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
- TalkIn/app/src/main/res/drawable/baseline_phone_iphone_24.xml
- TalkIn/app/src/main/res/layout/activity_mobile_auth.xml
> Mobile Number Verification screen Added

- TalkIn/app/src/main/java/com/example/talk_in/LogIn.kt
#121 Additional verification feature is now removed from login page
> Verification is removed from login page

- .idea/vcs.xml
- README.md
The methods and command lines for deploying the web app on Firebase Hosting are added. On running the commands on the android studio terminal in the root the application can be deployed and can be accessed using the domain on the Firebase Hosting.
> Readme update regarding Deploying of the TalkIn Web App using Firebase Hosting

- TalkIn/app/src/main/java/com/example/talk_in/ChatListFragment.kt
**Description**
#125 This PR updates the RecyclerView implementation in the Chat Activity to ensure that it displays all users.
> All users will now be displayed on Chat activity.

- Talk-In Webapp/lib/presentation/screens/home_screen.dart
- Talk-In Webapp/lib/presentation/screens/messaging_screen.dart
- Talk-In Webapp/lib/presentation/screens/notification_screen.dart
- Talk-In Webapp/lib/services/auth_service.dart
- Talk-In Webapp/lib/services/data_service.dart
- Talk-In Webapp/pubspec.lock
- Talk-In Webapp/pubspec.yaml
The web app now contains a messaging feature which will allow two users chat with each other.
https://github.com/Ijaiswalshivam/Talk-In/assets/101632079/ed01d54f-57d6-46b3-bd26-d4e3c83a73de
> Issue #120 Messaging feature between users in the Web App

- TalkIn/app/src/main/java/com/example/talk_in/EntryActivity.kt
- TalkIn/app/src/main/java/com/example/talk_in/LogIn.kt
- TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
#134 Fixed : At very first signup when user register then only verification is required, but not at login and if user login without verifying it then reject that process and shows that please verify your email.
> Now, the verification link will not be sent on the login page

- TalkIn/app/src/main/java/com/example/talk_in/LogIn.kt
- TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
- TalkIn/app/src/main/res/layout/activity_log_in.xml
- TalkIn/app/src/main/res/layout/activity_sign_up.xml
progress bar will displayed while login and signup process
> Progress bar added on login and signup

- .idea/Talk-In2.iml
- Talk-In Webapp/lib/main.dart
- Talk-In Webapp/lib/presentation/screens/find_people.dart
- Talk-In Webapp/lib/presentation/screens/home_screen.dart
- Talk-In Webapp/lib/presentation/screens/notification_screen.dart
- Talk-In Webapp/lib/presentation/screens/sign_in_screen.dart
- Talk-In Webapp/lib/presentation/screens/signup_screen.dart
- Talk-In Webapp/lib/services/auth_service.dart
- Talk-In Webapp/lib/services/data_service.dart
- Talk-In Webapp/pubspec.lock
- Talk-In Webapp/pubspec.yaml
The web app now contains certain UI fixes which are achieved using View Models and Change Notifiers in the code of the complete application. In the application progress bar are added wherever required. The website is made Dynamic using view models and Change Notifiers as a step towards implementing MVVM.
> Issue #140 Add UI Fixes like progress bar in web app along with View Models

- TalkIn/app/src/main/java/com/example/talk_in/ChatActivity.kt
- TalkIn/app/src/main/res/menu/user_chat_menu.xml
#156 Locate now button added in chat activity. Here is the screen shot
> Locate Now button added on chat activity

- Talk-In Webapp/lib/presentation/screens/find_people.dart
- Talk-In Webapp/lib/presentation/screens/home_screen.dart
- Talk-In Webapp/lib/presentation/screens/settings_screen.dart
- Talk-In Webapp/lib/services/auth_service.dart
- Talk-In Webapp/lib/services/data_service.dart
- Talk-In Webapp/pubspec.lock
- Talk-In Webapp/pubspec.yaml
- Talk-In Webapp/web/index.html
The tab contains the functionality to change profile image, change name, and change about. It also allows the functionality to hide profile image from non-friend people.
https://github.com/Ijaiswalshivam/Talk-In/assets/101632079/6b6b5b21-a97c-41a4-a502-26a67410aea4
> Issue #153 Setting tab in web app

- TalkIn/app/src/main/java/com/example/talk_in/MobileAuthActivity.kt
- TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
- TalkIn/app/src/main/java/com/example/talk_in/User.kt
- TalkIn/app/src/main/res/layout/activity_mobile_auth.xml
- TalkIn/app/src/main/res/layout/activity_sign_up.xml
#25 Mobile number authentication added
1. Go to Sign Up with mobile number activity
2. Submit your name and mobile number
3. Firebase will verify that you are not a robot 
4. Enter OTP
5. If you have entered correct OTP then you will be redirected to mainactivity.
6. If any user already exist then they will not be able to register with same phone number
> Mobile number authentication added

- .idea/misc.xml
- TalkIn/.idea/deploymentTargetSelector.xml
- TalkIn/app/build.gradle
- TalkIn/app/src/main/AndroidManifest.xml
- TalkIn/app/src/main/java/com/example/talk_in/ChatActivity.kt
- TalkIn/app/src/main/java/com/example/talk_in/MainActivity.kt
- TalkIn/app/src/main/res/layout/activity_chat.xml
- TalkIn/app/src/main/res/menu/user_chat_menu.xml
Reverts Ijaiswalshivam/Talk-In#155
Error In chat activity: Unresolved reference: locateNow,
and try to implement by forking it again so that i can merge this as soon as possible.
> Revert "Track Location of Chatting User Talk-IN"

- TalkIn/.idea/gradle.xml
- TalkIn/.idea/misc.xml
- TalkIn/.idea/vcs.xml
- TalkIn/app/build.gradle
- TalkIn/app/src/main/AndroidManifest.xml
- TalkIn/app/src/main/java/com/example/talk_in/ChatActivity.kt
- TalkIn/app/src/main/java/com/example/talk_in/FCMNotificationService.kt
- TalkIn/app/src/main/java/com/example/talk_in/FcmNotificationsSender.kt
- TalkIn/app/src/main/java/com/example/talk_in/LogIn.kt
- TalkIn/app/src/main/java/com/example/talk_in/MainActivity.kt
- TalkIn/app/src/main/res/layout/receive.xml
- TalkIn/app/src/main/res/layout/sent.xml
- TalkIn/app/src/main/res/values/strings.xml
FCm Notification Added
Sent and receive UI fix
> FCm Notifications added and etc. #19 #110 #138

- Talk-In Webapp/lib/presentation/screens/entry_screen.dart
- Talk-In Webapp/lib/services/auth_service.dart
- Talk-In Webapp/pubspec.lock
- Talk-In Webapp/pubspec.yaml
- Talk-In Webapp/web/index.html
The feature for google authentication is added successfully. Although for the features Facebook, Twitter and yahoo authentication code is added but will not work. The for those authentication will only work when the app get registered in developer account for the respective authentication providers. On receiving the ids and secrets, they are passed into the firebase account after that the authentication will work. The authentication for google is completed for now.
> Issue #166 Google, Facebook, Twitter and Yahoo Authentication in Web App

- TalkIn/app/src/main/java/com/example/talk_in/MobileAuthActivity.kt
- TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
- TalkIn/app/src/main/java/com/example/talk_in/User.kt
- TalkIn/app/src/main/java/com/example/talk_in/UserProfileScreen.kt
- TalkIn/app/src/main/res/layout/activity_user_profile_screen.xml
1. On Profile Screen activity. showLocation value will be fetched from database and whatever value it has it will get updated
2. By toggling the button it will reflect back the true or false value at database
> Toggle button added on profile screen for permission of location by user

- TalkIn/app/build.gradle
- TalkIn/app/google-services.json
- TalkIn/app/src/main/java/com/example/talk_in/EntryActivity.kt
#180 
User can login or signup with google account :
> Added Authentication with google in Kotlin app

- Talk-In Webapp/lib/presentation/screens/messaging_screen.dart
- Talk-In Webapp/lib/services/data_service.dart
- Talk-In Webapp/pubspec.lock
- Talk-In Webapp/pubspec.yaml
The user can now send media like image, pdf and audio within a size limit of 10 mb using the messaging screen.
> Issue #177 Send media in message screen to other user in web app

- .idea/misc.xml
- TalkIn/app/.idea/gradle.xml
- TalkIn/app/.idea/misc.xml
- TalkIn/app/.idea/modules.xml
- TalkIn/app/build.gradle
- TalkIn/app/src/main/java/com/example/talk_in/ChatActivity.kt
- TalkIn/app/src/main/java/com/example/talk_in/EntryActivity.kt
- TalkIn/app/src/main/java/com/example/talk_in/LogIn.kt
- TalkIn/app/src/main/java/com/example/talk_in/MainActivity.kt
- TalkIn/app/src/main/java/com/example/talk_in/MobileAuthActivity.kt
- TalkIn/app/src/main/java/com/example/talk_in/ResetPasswordActivity.kt
- TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
- TalkIn/app/src/main/java/com/example/talk_in/UserProfileScreen.kt
I dont have Screenshot as i changed the code in all the pages to use Viewbinding and refractored findViewbyId to Viewbinding .
> Updated Code to Use Viewbinding

- TalkIn/app/src/main/java/com/example/talk_in/UserProfileScreen.kt
#196 Preview:
https://github.com/Ijaiswalshivam/Talk-In/assets/105499099/0d254c0d-8192-48bb-8a65-bd8ffcb7e303
> Fixed: User Profile Screen will show receiver users profile when clicked on view profile

- Talk-In Webapp/lib/presentation/screens/group_chat_screen.dart
- Talk-In Webapp/lib/presentation/screens/home_screen.dart
- Talk-In Webapp/lib/presentation/screens/my_group_screen.dart
- Talk-In Webapp/lib/services/data_service.dart
- Talk-In Webapp/web/index.html
The app now holds the functionality to perform group chat among more than 1 users at the same time. In the video conversation between 3 friends is shown.
https://github.com/Ijaiswalshivam/Talk-In/assets/101632079/579c1835-788d-436e-9e05-5bd00d17986b
> Issue #193 Group chat feature in web app

- TalkIn/app/src/main/java/com/example/talk_in/EntryActivity.kt
- TalkIn/app/src/main/java/com/example/talk_in/MobileAuthActivity.kt
- TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
- TalkIn/app/src/main/java/com/example/talk_in/User.kt
- TalkIn/app/src/main/java/com/example/talk_in/UserAdapter.kt
- TalkIn/app/src/main/java/com/example/talk_in/UserProfileScreen.kt
- TalkIn/app/src/main/res/layout/activity_user_profile_screen.xml
- TalkIn/app/src/main/res/layout/custom_dialog_layout.xml
#201 
1. User will be able to update his about section and it will reflect on database
https://github.com/Ijaiswalshivam/Talk-In/assets/105499099/4837581e-2c4b-4c1f-9422-8caea3c27e37
2. whoever has updated his profile picture all the user can see it on mainactivity
3. Screenshot is attached below
> Fix: User can update his about section and on mainactivity user's profile picture will be shown

- TalkIn/app/src/main/java/com/example/talk_in/FCMNotificationService.kt
changes made for PENDING INTENT
> App ShutDown For Android 12 and Above fixed #203

- Talk-In Webapp/lib/presentation/screens/messaging_screen.dart
- Talk-In Webapp/lib/presentation/screens/profile_screen.dart
- Talk-In Webapp/lib/presentation/screens/settings_screen.dart
- Talk-In Webapp/pubspec.lock
- Talk-In Webapp/pubspec.yaml
Info like name, about , email and mutual friends is shown.
https://github.com/Ijaiswalshivam/Talk-In/assets/101632079/bbd9efb2-1174-4f66-b425-173e354c4ae5
> Issue #204 Users can view other people profile

- Talk-In Webapp/lib/presentation/screens/messaging_screen.dart
> Issue #205 add time stamp in message

- TalkIn/app/src/main/java/com/example/talk_in/LogIn.kt
- TalkIn/app/src/main/java/com/example/talk_in/MainActivity.kt
- TalkIn/app/src/main/java/com/example/talk_in/MobileAuthActivity.kt
- TalkIn/app/src/main/java/com/example/talk_in/UserProfileScreen.kt
#208 
After this fix user cannot see or chat with other users after logout.
> Fixed: User will not be able to see main activity after logout

- Talk-In Webapp/lib/presentation/screens/sign_in_screen.dart
- Talk-In Webapp/lib/services/auth_service.dart
An email is sent to the user from where the user can reset the password.  After resetting the password the user type the new password to logIn.
https://github.com/Ijaiswalshivam/Talk-In/assets/101632079/1718a872-8212-4d1b-a0a3-bf03ebf1ec1f
> Issue #213 Forgot Password feature in web app

- TalkIn/app/src/main/java/com/example/talk_in/EntryActivity.kt
- TalkIn/app/src/main/java/com/example/talk_in/LogIn.kt
- TalkIn/app/src/main/java/com/example/talk_in/MainActivity.kt
- TalkIn/app/src/main/java/com/example/talk_in/MobileAuthActivity.kt
- TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
- TalkIn/app/src/main/java/com/example/talk_in/User.kt
- TalkIn/app/src/main/java/com/example/talk_in/UserProfileScreen.kt
> Fix: Unverified users will not be displayed on mainactivity

- Talk-In Webapp/lib/presentation/screens/find_people.dart
- Talk-In Webapp/lib/services/data_service.dart
https://github.com/Ijaiswalshivam/Talk-In/assets/101632079/762e01d3-d0ca-4b0e-83ca-5997bccf4aed
> Issue #216 Unfriend functionality in web app

- TalkIn/app/src/main/res/layout/receive.xml
- TalkIn/app/src/main/res/layout/sent.xml
> Chat UI Fixed #231

- TalkIn/app/src/main/java/com/example/talk_in/UserAdapter.kt
- TalkIn/app/src/main/res/layout/user_layout.xml
#223 
1. User will be able to see the last message in the conversation on MainActivity. If there is no conversation between two users, then it will show the receiver user's status.
2. If a message is longer than 30 characters, then it will be truncated to 30 characters by adding '...'.
Screen shot is attached here:
> Add: Last message of the chat between sender and receiver will be showing

- Talk-In Webapp/lib/presentation/screens/group_chat_screen.dart
- Talk-In Webapp/lib/presentation/screens/group_profile.dart
- Talk-In Webapp/lib/presentation/screens/home_screen.dart
> Issue #227 Manage Group profile/settings

- TalkIn/app/src/main/res/layout/user_layout.xml
> update user_layout.xml , Fixed #239

- TalkIn/app/src/main/java/com/example/talk_in/ChatActivity.kt
Fix: #207 
1. User can see receiver user's profile picture while chatting with them
2. User can see receiver user's profile by clicking on View Profile
3. Whenever message in messagebox is empty user cannot send message and send icon will become dull and if messagebox is not empty it will become dark and user can send message.
Here are the screenshots:
> Fix: User is not able to see receiver user's profile and also user is not able to see profile picture of receiver user while chatting with them

- Talk-In Webapp/lib/main.dart
- Talk-In Webapp/lib/presentation/screens/splash_screen.dart
https://github.com/Ijaiswalshivam/Talk-In/assets/101632079/69b16ffa-94c9-4017-875b-2aa876baccf3
> Issue #238 Splash screen in web app

- TalkIn/app/src/main/java/com/example/talk_in/UserProfileScreen.kt
- TalkIn/app/src/main/res/layout/activity_user_profile_screen.xml
#235 
https://github.com/Ijaiswalshivam/Talk-In/assets/105499099/bbcc0e70-4cbd-4c26-91af-d192a47aab85
> Fixed: User is not able to update his about me section in his profile

- TalkIn/app/src/main/java/com/example/talk_in/AESUtils.java
- TalkIn/app/src/main/java/com/example/talk_in/ChatActivity.kt
- TalkIn/app/src/main/java/com/example/talk_in/Message.kt
- TalkIn/app/src/main/java/com/example/talk_in/MessageAdapter.kt
- TalkIn/app/src/main/java/com/example/talk_in/UserAdapter.kt
#246 
**Message Encryption:**
When a user sends a message to another user, the message will be encrypted using the Advanced Encryption Standard (AES).
**Message Decryption:**
Upon receiving the message, the app will decrypt it using AES.
> Add: Message Encryption and Decryption added

- TalkIn/app/src/main/java/com/example/talk_in/UserAdapter.kt
- TalkIn/app/src/main/res/layout/activity_chat.xml
- TalkIn/app/src/main/res/layout/user_layout.xml
> Fixed: Profile picture in chat activity & in main activity is not properly displayed

- Talk-In Webapp/lib/presentation/screens/group_chat_screen.dart
- Talk-In Webapp/lib/presentation/screens/messaging_screen.dart
- Talk-In Webapp/lib/services/encryption_service.dart
Added Vigenere cipher algorithm for encryption and decryption of text.
> Issue #245 message encryption in web app

- TalkIn/app/src/main/res/drawable/baseline_remove_red_eye_24.xml
- TalkIn/app/src/main/res/layout/activity_log_in.xml
- TalkIn/app/src/main/res/layout/activity_sign_up.xml
Applied to sign up and sign in
https://github.com/Ijaiswalshivam/Talk-In/assets/101632079/72b8a0a1-34ea-4d46-a3e1-04fa17176aab
> Obscure Password functionality in android app

- TalkIn/app/src/main/java/com/example/talk_in/UserAdapter.kt
- TalkIn/app/src/main/res/layout/user_layout.xml
> Fixed: In mainactivity name is not showing properly

- TalkIn/app/src/main/java/com/example/talk_in/MainActivity.kt
- TalkIn/app/src/main/res/drawable/custom_searchbar_background.xml
- TalkIn/app/src/main/res/layout/activity_main.xml
#263 
https://github.com/Ijaiswalshivam/Talk-In/assets/105499099/828f295e-f13a-41fe-afbf-2d90954f6638
> Fix: Search bar modification

- TalkIn/app/src/main/java/com/example/talk_in/EntryActivity.kt
- TalkIn/app/src/main/java/com/example/talk_in/MobileAuthActivity.kt
- TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
- TalkIn/app/src/main/java/com/example/talk_in/User.kt
- TalkIn/app/src/main/res/layout/activity_mobile_auth.xml
- TalkIn/app/src/main/res/layout/activity_sign_up.xml
> Talk in ID feature is now live.

- TalkIn/app/src/main/java/com/example/talk_in/EntryActivity.kt
- TalkIn/app/src/main/java/com/example/talk_in/MobileAuthActivity.kt
- TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
- TalkIn/app/src/main/java/com/example/talk_in/User.kt
- TalkIn/app/src/main/res/layout/activity_mobile_auth.xml
- TalkIn/app/src/main/res/layout/activity_sign_up.xml
Reverts Ijaiswalshivam/Talk-In#278
> Revert "Talk in ID feature is now live."

- TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
- TalkIn/app/src/main/res/layout/activity_sign_up.xml
#277 
https://github.com/Ijaiswalshivam/Talk-In/assets/105499099/c612456e-01b6-438b-b14f-d9ba3e03ca1e
> Fixed: Signup page should ask for confirm password
